version: '3.8'

services:
  moonboard-server:
    build: ./predicting
    container_name: moonboard-server
    ports:
     - 5000:5000
    networks:
     - moonboard

  moonboard-app:
    tty: true
    build: ./front-end
    container_name: moonboard-app
    depends_on:
     - moonboard-server
    ports: 
     - 3000:3000
    networks:
     - moonboard

networks:
  moonboard: 
